export const LearningObjectSheetColumnNames = [
    'LO',
    'LO Title',
    'Screen Number',
    'Activity type name',
    'Layout info',
    'Rubric',
    'Contents',
    'Supplement area (content assets)',
    'Attachment area 1 (pinned object)',
    'Attachment 2 (pinned object)',
    'Media in header',
    'Media in header screens info',
    'Feedback band 1 (Correct)',
    'Feedback band 2 (Incorrect)',
    'Feedback Threshold',
    'LO global options',
    'LO screen specific options',
    'Additional notes',
    'R1 build comments',
    'R1 check comments',
    'R2 build comments',
    'R2 check comments',
    'RC build comments',
    'RC check comments'
]